/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import fabrica.Fabrica;
import interfaces.IControlador;
import java.time.Clock;
import java.util.Date;

/**
 *
 * @author lucho
 */
public class inicio extends javax.swing.JFrame {
    Fabrica fabrica = new Fabrica();
    IControlador IControlador = fabrica.getInterface();
    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogDepartamentoDuplicado = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonDepartamentoDuplicadoCancelar = new javax.swing.JButton();
        jButtonDepartamentoDuplicadoReingresar = new javax.swing.JButton();
        jTabbedPaneCasosDeUso = new javax.swing.JTabbedPane();
        jInternalFrameAgregarUsuario = new javax.swing.JInternalFrame();
        jInternalFrameConsultarUsuario = new javax.swing.JInternalFrame();
        jInternalFrameModificarUsuario = new javax.swing.JInternalFrame();
        jInternalFrameAltaActividadTuristica = new javax.swing.JInternalFrame();
        jInternalFrameConsultaActividadTuristica = new javax.swing.JInternalFrame();
        jInternalFrameAltaDepartamento = new javax.swing.JInternalFrame();
        jTextFieldNombreDepartamento = new javax.swing.JTextField();
        jLabelNombreDepartamento = new javax.swing.JLabel();
        jLabelDescripcionDepartamento = new javax.swing.JLabel();
        jTextFieldDescripcionDepartamento = new javax.swing.JTextField();
        jTextFieldURLDepartamento = new javax.swing.JTextField();
        jLabelURLDepartamento = new javax.swing.JLabel();
        jButtonAltaDepartamentoVaciarCampos = new javax.swing.JButton();
        jButtonAltaDepartamentoEnviar = new javax.swing.JButton();
        jSeparatorAltaDepartamento = new javax.swing.JSeparator();
        jInternalFrameConsultaSalidaTuristica = new javax.swing.JInternalFrame();
        jInternalFrameInscripcionSalidaTuristica = new javax.swing.JInternalFrame();
        jInternalFrameAltaPaqueteActividades = new javax.swing.JInternalFrame();
        jInternalFrameAgregarActividadPaquete = new javax.swing.JInternalFrame();
        jInternalFrameConsultaPaquetes = new javax.swing.JInternalFrame();
        jInternalFrameAltaSalidaTuristica = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxDepartamento = new javax.swing.JComboBox<>();
        jComboBoxActividad = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombreSalida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldLugarSalida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSpinnerCantMaxTuristas = new javax.swing.JSpinner();
        jSpinnerFechaSalida = new javax.swing.JSpinner();
        jSpinnerFechaAlta = new javax.swing.JSpinner();
        jButtonAltaSalidaVaciarCampos = new javax.swing.JButton();
        jButtonAltaSalidaEnviar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAcciones = new javax.swing.JMenu();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuUsuarioAlta = new javax.swing.JMenuItem();
        jMenuUsuarioConsulta = new javax.swing.JMenuItem();
        jMenuUsuarioModificar = new javax.swing.JMenuItem();
        jMenuActividad = new javax.swing.JMenu();
        jMenuActividadAlta = new javax.swing.JMenuItem();
        jMenuActividadConsulta = new javax.swing.JMenuItem();
        jMenuDepartamentoAlta = new javax.swing.JMenuItem();
        jMenuSalida = new javax.swing.JMenu();
        jMenuSalidaAlta = new javax.swing.JMenuItem();
        jMenuSalidaConsulta = new javax.swing.JMenuItem();
        jMenuSalidaInscripcion = new javax.swing.JMenuItem();
        jMenuPaquete = new javax.swing.JMenu();
        jMenuAltaPaquete = new javax.swing.JMenuItem();
        jMenuAgregarActividadPaquete = new javax.swing.JMenuItem();
        jMenuConsultaPaquete = new javax.swing.JMenuItem();

        jDialogDepartamentoDuplicado.setTitle("ERROR");
        jDialogDepartamentoDuplicado.setMinimumSize(new java.awt.Dimension(400, 250));
        jDialogDepartamentoDuplicado.setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Ya existe un departamento ingresado en el sistema con ese nombre!.\nSeleccione 'Cancelar' para volver atras y descartar los datos ingresados o \"Reingresar\" para volver atras y modificar los datos");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonDepartamentoDuplicadoCancelar.setText("Cancelar");
        jButtonDepartamentoDuplicadoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepartamentoDuplicadoCancelarActionPerformed(evt);
            }
        });

        jButtonDepartamentoDuplicadoReingresar.setText("Reingresar");
        jButtonDepartamentoDuplicadoReingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepartamentoDuplicadoReingresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogDepartamentoDuplicadoLayout = new javax.swing.GroupLayout(jDialogDepartamentoDuplicado.getContentPane());
        jDialogDepartamentoDuplicado.getContentPane().setLayout(jDialogDepartamentoDuplicadoLayout);
        jDialogDepartamentoDuplicadoLayout.setHorizontalGroup(
            jDialogDepartamentoDuplicadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogDepartamentoDuplicadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogDepartamentoDuplicadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(jDialogDepartamentoDuplicadoLayout.createSequentialGroup()
                        .addComponent(jButtonDepartamentoDuplicadoCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDepartamentoDuplicadoReingresar)))
                .addContainerGap())
        );
        jDialogDepartamentoDuplicadoLayout.setVerticalGroup(
            jDialogDepartamentoDuplicadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogDepartamentoDuplicadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jDialogDepartamentoDuplicadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDepartamentoDuplicadoCancelar)
                    .addComponent(jButtonDepartamentoDuplicadoReingresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("G1 - Programación de Aplicaciones");
        setMinimumSize(new java.awt.Dimension(800, 600));

        jTabbedPaneCasosDeUso.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPaneCasosDeUso.setToolTipText("");

        jInternalFrameAgregarUsuario.setVisible(true);

        javax.swing.GroupLayout jInternalFrameAgregarUsuarioLayout = new javax.swing.GroupLayout(jInternalFrameAgregarUsuario.getContentPane());
        jInternalFrameAgregarUsuario.getContentPane().setLayout(jInternalFrameAgregarUsuarioLayout);
        jInternalFrameAgregarUsuarioLayout.setHorizontalGroup(
            jInternalFrameAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrameAgregarUsuarioLayout.setVerticalGroup(
            jInternalFrameAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPaneCasosDeUso.addTab("Agregar Usuario", jInternalFrameAgregarUsuario);

        jInternalFrameConsultarUsuario.setVisible(true);

        javax.swing.GroupLayout jInternalFrameConsultarUsuarioLayout = new javax.swing.GroupLayout(jInternalFrameConsultarUsuario.getContentPane());
        jInternalFrameConsultarUsuario.getContentPane().setLayout(jInternalFrameConsultarUsuarioLayout);
        jInternalFrameConsultarUsuarioLayout.setHorizontalGroup(
            jInternalFrameConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrameConsultarUsuarioLayout.setVerticalGroup(
            jInternalFrameConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPaneCasosDeUso.addTab("Consultar Usuario", jInternalFrameConsultarUsuario);

        jInternalFrameModificarUsuario.setVisible(true);

        javax.swing.GroupLayout jInternalFrameModificarUsuarioLayout = new javax.swing.GroupLayout(jInternalFrameModificarUsuario.getContentPane());
        jInternalFrameModificarUsuario.getContentPane().setLayout(jInternalFrameModificarUsuarioLayout);
        jInternalFrameModificarUsuarioLayout.setHorizontalGroup(
            jInternalFrameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrameModificarUsuarioLayout.setVerticalGroup(
            jInternalFrameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPaneCasosDeUso.addTab("Modificar Usuario", jInternalFrameModificarUsuario);

        jInternalFrameAltaActividadTuristica.setVisible(true);

        javax.swing.GroupLayout jInternalFrameAltaActividadTuristicaLayout = new javax.swing.GroupLayout(jInternalFrameAltaActividadTuristica.getContentPane());
        jInternalFrameAltaActividadTuristica.getContentPane().setLayout(jInternalFrameAltaActividadTuristicaLayout);
        jInternalFrameAltaActividadTuristicaLayout.setHorizontalGroup(
            jInternalFrameAltaActividadTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrameAltaActividadTuristicaLayout.setVerticalGroup(
            jInternalFrameAltaActividadTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPaneCasosDeUso.addTab("Alta Actividad Turística", jInternalFrameAltaActividadTuristica);

        jInternalFrameConsultaActividadTuristica.setVisible(true);

        javax.swing.GroupLayout jInternalFrameConsultaActividadTuristicaLayout = new javax.swing.GroupLayout(jInternalFrameConsultaActividadTuristica.getContentPane());
        jInternalFrameConsultaActividadTuristica.getContentPane().setLayout(jInternalFrameConsultaActividadTuristicaLayout);
        jInternalFrameConsultaActividadTuristicaLayout.setHorizontalGroup(
            jInternalFrameConsultaActividadTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrameConsultaActividadTuristicaLayout.setVerticalGroup(
            jInternalFrameConsultaActividadTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPaneCasosDeUso.addTab("Consulta Actividad Turística", jInternalFrameConsultaActividadTuristica);

        jInternalFrameAltaDepartamento.setVisible(true);

        jTextFieldNombreDepartamento.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabelNombreDepartamento.setText("Nombre departamento");

        jLabelDescripcionDepartamento.setText("Descripción departamento");

        jTextFieldURLDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldURLDepartamentoActionPerformed(evt);
            }
        });

        jLabelURLDepartamento.setText("URL");

        jButtonAltaDepartamentoVaciarCampos.setText("vaciar campos");
        jButtonAltaDepartamentoVaciarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaDepartamentoVaciarCamposActionPerformed(evt);
            }
        });

        jButtonAltaDepartamentoEnviar.setText("enviar");
        jButtonAltaDepartamentoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaDepartamentoEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameAltaDepartamentoLayout = new javax.swing.GroupLayout(jInternalFrameAltaDepartamento.getContentPane());
        jInternalFrameAltaDepartamento.getContentPane().setLayout(jInternalFrameAltaDepartamentoLayout);
        jInternalFrameAltaDepartamentoLayout.setHorizontalGroup(
            jInternalFrameAltaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameAltaDepartamentoLayout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addGroup(jInternalFrameAltaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNombreDepartamento)
                    .addComponent(jTextFieldNombreDepartamento)
                    .addComponent(jTextFieldDescripcionDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(jLabelDescripcionDepartamento)
                    .addComponent(jLabelURLDepartamento)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameAltaDepartamentoLayout.createSequentialGroup()
                        .addComponent(jButtonAltaDepartamentoVaciarCampos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAltaDepartamentoEnviar))
                    .addComponent(jTextFieldURLDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(jSeparatorAltaDepartamento))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jInternalFrameAltaDepartamentoLayout.setVerticalGroup(
            jInternalFrameAltaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameAltaDepartamentoLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabelNombreDepartamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNombreDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jLabelDescripcionDepartamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDescripcionDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jLabelURLDepartamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldURLDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jSeparatorAltaDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameAltaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAltaDepartamentoVaciarCampos)
                    .addComponent(jButtonAltaDepartamentoEnviar))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jTabbedPaneCasosDeUso.addTab("Alta Departamento", jInternalFrameAltaDepartamento);

        jInternalFrameConsultaSalidaTuristica.setVisible(true);

        javax.swing.GroupLayout jInternalFrameConsultaSalidaTuristicaLayout = new javax.swing.GroupLayout(jInternalFrameConsultaSalidaTuristica.getContentPane());
        jInternalFrameConsultaSalidaTuristica.getContentPane().setLayout(jInternalFrameConsultaSalidaTuristicaLayout);
        jInternalFrameConsultaSalidaTuristicaLayout.setHorizontalGroup(
            jInternalFrameConsultaSalidaTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrameConsultaSalidaTuristicaLayout.setVerticalGroup(
            jInternalFrameConsultaSalidaTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPaneCasosDeUso.addTab("Consulta Salida Turística", jInternalFrameConsultaSalidaTuristica);

        jInternalFrameInscripcionSalidaTuristica.setVisible(true);

        javax.swing.GroupLayout jInternalFrameInscripcionSalidaTuristicaLayout = new javax.swing.GroupLayout(jInternalFrameInscripcionSalidaTuristica.getContentPane());
        jInternalFrameInscripcionSalidaTuristica.getContentPane().setLayout(jInternalFrameInscripcionSalidaTuristicaLayout);
        jInternalFrameInscripcionSalidaTuristicaLayout.setHorizontalGroup(
            jInternalFrameInscripcionSalidaTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrameInscripcionSalidaTuristicaLayout.setVerticalGroup(
            jInternalFrameInscripcionSalidaTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPaneCasosDeUso.addTab("Inscripcion a Salida Turística", jInternalFrameInscripcionSalidaTuristica);

        jInternalFrameAltaPaqueteActividades.setVisible(true);

        javax.swing.GroupLayout jInternalFrameAltaPaqueteActividadesLayout = new javax.swing.GroupLayout(jInternalFrameAltaPaqueteActividades.getContentPane());
        jInternalFrameAltaPaqueteActividades.getContentPane().setLayout(jInternalFrameAltaPaqueteActividadesLayout);
        jInternalFrameAltaPaqueteActividadesLayout.setHorizontalGroup(
            jInternalFrameAltaPaqueteActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrameAltaPaqueteActividadesLayout.setVerticalGroup(
            jInternalFrameAltaPaqueteActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPaneCasosDeUso.addTab("Alta Paquete de Actividades Turísticas", jInternalFrameAltaPaqueteActividades);

        jInternalFrameAgregarActividadPaquete.setVisible(true);

        javax.swing.GroupLayout jInternalFrameAgregarActividadPaqueteLayout = new javax.swing.GroupLayout(jInternalFrameAgregarActividadPaquete.getContentPane());
        jInternalFrameAgregarActividadPaquete.getContentPane().setLayout(jInternalFrameAgregarActividadPaqueteLayout);
        jInternalFrameAgregarActividadPaqueteLayout.setHorizontalGroup(
            jInternalFrameAgregarActividadPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrameAgregarActividadPaqueteLayout.setVerticalGroup(
            jInternalFrameAgregarActividadPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPaneCasosDeUso.addTab("Agregar Actividad Turística a Paquete", jInternalFrameAgregarActividadPaquete);

        jInternalFrameConsultaPaquetes.setVisible(true);

        javax.swing.GroupLayout jInternalFrameConsultaPaquetesLayout = new javax.swing.GroupLayout(jInternalFrameConsultaPaquetes.getContentPane());
        jInternalFrameConsultaPaquetes.getContentPane().setLayout(jInternalFrameConsultaPaquetesLayout);
        jInternalFrameConsultaPaquetesLayout.setHorizontalGroup(
            jInternalFrameConsultaPaquetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrameConsultaPaquetesLayout.setVerticalGroup(
            jInternalFrameConsultaPaquetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPaneCasosDeUso.addTab("Consulta de Paquetes", jInternalFrameConsultaPaquetes);

        jInternalFrameAltaSalidaTuristica.setVisible(true);

        jLabel1.setText("Departamento:");

        jComboBoxDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Departamento" }));

        jComboBoxActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Actividad" }));

        jLabel2.setText("Actividad:");

        jLabel3.setText("Nombre de Salida:");

        jTextFieldNombreSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreSalidaActionPerformed(evt);
            }
        });

        jLabel4.setText("Lugar de Salida:");

        jTextFieldLugarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLugarSalidaActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha/Hora de Salida:");

        jLabel6.setText("Fecha de Alta:");

        jLabel7.setText("Cantidad máxima de turistas:");

        jSpinnerCantMaxTuristas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSpinnerFechaSalida.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR_OF_DAY));

        jSpinnerFechaAlta.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR_OF_DAY));

        jButtonAltaSalidaVaciarCampos.setText("vaciar campos");
        jButtonAltaSalidaVaciarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaSalidaVaciarCamposActionPerformed(evt);
            }
        });

        jButtonAltaSalidaEnviar.setText("enviar");
        jButtonAltaSalidaEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaSalidaEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameAltaSalidaTuristicaLayout = new javax.swing.GroupLayout(jInternalFrameAltaSalidaTuristica.getContentPane());
        jInternalFrameAltaSalidaTuristica.getContentPane().setLayout(jInternalFrameAltaSalidaTuristicaLayout);
        jInternalFrameAltaSalidaTuristicaLayout.setHorizontalGroup(
            jInternalFrameAltaSalidaTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createSequentialGroup()
                        .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createSequentialGroup()
                                .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3)
                                            .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBoxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextFieldNombreSalida))
                                        .addComponent(jButtonAltaSalidaVaciarCampos)))
                                .addGap(66, 66, 66))
                            .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createSequentialGroup()
                                .addComponent(jSpinnerFechaSalida)
                                .addGap(202, 202, 202)))
                        .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxActividad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel4)
                                .addComponent(jTextFieldLugarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jSpinnerCantMaxTuristas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonAltaSalidaEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSpinnerFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jInternalFrameAltaSalidaTuristicaLayout.setVerticalGroup(
            jInternalFrameAltaSalidaTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombreSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldLugarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerCantMaxTuristas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addGroup(jInternalFrameAltaSalidaTuristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAltaSalidaVaciarCampos)
                    .addComponent(jButtonAltaSalidaEnviar))
                .addGap(22, 22, 22))
        );

        jTabbedPaneCasosDeUso.addTab("Alta Salida Turística", jInternalFrameAltaSalidaTuristica);

        jMenuAcciones.setText("Acciones");

        jMenuUsuario.setText("Usuarios");

        jMenuUsuarioAlta.setText("Alta de Usuario");
        jMenuUsuarioAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioAltaActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuUsuarioAlta);

        jMenuUsuarioConsulta.setText("Consulta de Usuario");
        jMenuUsuarioConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioConsultaActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuUsuarioConsulta);

        jMenuUsuarioModificar.setText("Modificar Datos de Usuario");
        jMenuUsuarioModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioModificarActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuUsuarioModificar);

        jMenuAcciones.add(jMenuUsuario);

        jMenuActividad.setText("Actividad Turistica");

        jMenuActividadAlta.setText("Alta de Actividad");
        jMenuActividadAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActividadAltaActionPerformed(evt);
            }
        });
        jMenuActividad.add(jMenuActividadAlta);

        jMenuActividadConsulta.setText("Consulta de Actividad");
        jMenuActividadConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActividadConsultaActionPerformed(evt);
            }
        });
        jMenuActividad.add(jMenuActividadConsulta);

        jMenuDepartamentoAlta.setText("Alta de Departamento");
        jMenuDepartamentoAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDepartamentoAltaActionPerformed(evt);
            }
        });
        jMenuActividad.add(jMenuDepartamentoAlta);

        jMenuAcciones.add(jMenuActividad);

        jMenuSalida.setText("Salida Turistica");

        jMenuSalidaAlta.setText("Alta de Salida");
        jMenuSalidaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalidaAltaActionPerformed(evt);
            }
        });
        jMenuSalida.add(jMenuSalidaAlta);

        jMenuSalidaConsulta.setText("Consulta de Salida");
        jMenuSalidaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalidaConsultaActionPerformed(evt);
            }
        });
        jMenuSalida.add(jMenuSalidaConsulta);

        jMenuSalidaInscripcion.setText("Inscripción a Salida");
        jMenuSalidaInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalidaInscripcionActionPerformed(evt);
            }
        });
        jMenuSalida.add(jMenuSalidaInscripcion);

        jMenuAcciones.add(jMenuSalida);

        jMenuPaquete.setText("Paquetes");

        jMenuAltaPaquete.setText("Alta Paquete de Actividades Turísticas");
        jMenuAltaPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAltaPaqueteActionPerformed(evt);
            }
        });
        jMenuPaquete.add(jMenuAltaPaquete);

        jMenuAgregarActividadPaquete.setText("Agregar Actividad Turística a Paquete");
        jMenuAgregarActividadPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAgregarActividadPaqueteActionPerformed(evt);
            }
        });
        jMenuPaquete.add(jMenuAgregarActividadPaquete);

        jMenuConsultaPaquete.setText("Consulta de Paquetes");
        jMenuConsultaPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultaPaqueteActionPerformed(evt);
            }
        });
        jMenuPaquete.add(jMenuConsultaPaquete);

        jMenuAcciones.add(jMenuPaquete);

        jMenuBar1.add(jMenuAcciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneCasosDeUso)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneCasosDeUso)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuUsuarioAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioAltaActionPerformed
        // TODO add your handling code here:
        jTabbedPaneCasosDeUso.setSelectedIndex(0);
        
    }//GEN-LAST:event_jMenuUsuarioAltaActionPerformed

    private void jMenuSalidaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalidaAltaActionPerformed
        // TODO add your handling code here:
        jTabbedPaneCasosDeUso.setSelectedIndex(6);
    }//GEN-LAST:event_jMenuSalidaAltaActionPerformed

    private void jMenuDepartamentoAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDepartamentoAltaActionPerformed
        jTabbedPaneCasosDeUso.setSelectedIndex(5);
    }//GEN-LAST:event_jMenuDepartamentoAltaActionPerformed

    private void jMenuUsuarioConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioConsultaActionPerformed
        // TODO add your handling code here:
        jTabbedPaneCasosDeUso.setSelectedIndex(1);
    }//GEN-LAST:event_jMenuUsuarioConsultaActionPerformed

    private void jMenuUsuarioModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioModificarActionPerformed
        // TODO add your handling code here:
        jTabbedPaneCasosDeUso.setSelectedIndex(2);
    }//GEN-LAST:event_jMenuUsuarioModificarActionPerformed

    private void jMenuActividadAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActividadAltaActionPerformed
        // TODO add your handling code here:
        jTabbedPaneCasosDeUso.setSelectedIndex(3);
    }//GEN-LAST:event_jMenuActividadAltaActionPerformed

    private void jMenuActividadConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActividadConsultaActionPerformed
        // TODO add your handling code here:
        jTabbedPaneCasosDeUso.setSelectedIndex(4);
    }//GEN-LAST:event_jMenuActividadConsultaActionPerformed

    private void jMenuSalidaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalidaConsultaActionPerformed
        // TODO add your handling code here:
        jTabbedPaneCasosDeUso.setSelectedIndex(7);
    }//GEN-LAST:event_jMenuSalidaConsultaActionPerformed

    private void jMenuSalidaInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalidaInscripcionActionPerformed
        // TODO add your handling code here:
        jTabbedPaneCasosDeUso.setSelectedIndex(8);
    }//GEN-LAST:event_jMenuSalidaInscripcionActionPerformed

    private void jMenuConsultaPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultaPaqueteActionPerformed
        // TODO add your handling code here:
        jTabbedPaneCasosDeUso.setSelectedIndex(11);
    }//GEN-LAST:event_jMenuConsultaPaqueteActionPerformed

    private void jMenuAltaPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAltaPaqueteActionPerformed
        // TODO add your handling code here:
        jTabbedPaneCasosDeUso.setSelectedIndex(9);
    }//GEN-LAST:event_jMenuAltaPaqueteActionPerformed

    private void jMenuAgregarActividadPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAgregarActividadPaqueteActionPerformed
        // TODO add your handling code here:
        jTabbedPaneCasosDeUso.setSelectedIndex(10);
    }//GEN-LAST:event_jMenuAgregarActividadPaqueteActionPerformed

    private void jTextFieldURLDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldURLDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldURLDepartamentoActionPerformed

    private void jButtonAltaDepartamentoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaDepartamentoEnviarActionPerformed
        // TODO add your handling code here:
        String nombre = jTextFieldNombreDepartamento.getText();
        String descripcion = jTextFieldDescripcionDepartamento.getText();
        String url = jTextFieldURLDepartamento.getText();
        
        if(IControlador.existeDepartamento(nombre)){
            jDialogDepartamentoDuplicado.setVisible(true);
        }else{
            IControlador.altaDepartamento(nombre,descripcion,url);
            jTextFieldNombreDepartamento.setText("");
            jTextFieldDescripcionDepartamento.setText("");
            jTextFieldURLDepartamento.setText("");
        }   
    }//GEN-LAST:event_jButtonAltaDepartamentoEnviarActionPerformed

    private void jButtonAltaDepartamentoVaciarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaDepartamentoVaciarCamposActionPerformed
        // TODO add your handling code here:
        jTextFieldNombreDepartamento.setText("");
        jTextFieldDescripcionDepartamento.setText("");
        jTextFieldURLDepartamento.setText("");
    }//GEN-LAST:event_jButtonAltaDepartamentoVaciarCamposActionPerformed

    private void jButtonDepartamentoDuplicadoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepartamentoDuplicadoCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldNombreDepartamento.setText("");
        jTextFieldDescripcionDepartamento.setText("");
        jTextFieldURLDepartamento.setText("");
        jDialogDepartamentoDuplicado.setVisible(false);
    }//GEN-LAST:event_jButtonDepartamentoDuplicadoCancelarActionPerformed

    private void jButtonDepartamentoDuplicadoReingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepartamentoDuplicadoReingresarActionPerformed
        // TODO add your handling code here:
        jDialogDepartamentoDuplicado.setVisible(false);
    }//GEN-LAST:event_jButtonDepartamentoDuplicadoReingresarActionPerformed

    private void jTextFieldNombreSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreSalidaActionPerformed

    private void jTextFieldLugarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLugarSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLugarSalidaActionPerformed

    private void jButtonAltaSalidaVaciarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaSalidaVaciarCamposActionPerformed
        // Se limpian los campos del panel "Alta de Salida Turistica"
        jComboBoxDepartamento.setSelectedIndex(0);
        
        // Guardamos el valor por defecto para limpiar el combobox
        String defaultValue = jComboBoxActividad.getItemAt(0);
        jComboBoxActividad.removeAllItems();
        jComboBoxActividad.addItem(defaultValue);
        
        jTextFieldNombreSalida.setText("");
        jTextFieldLugarSalida.setText("");
        
        jSpinnerFechaSalida.setValue(new Date());
        jSpinnerFechaAlta.setValue(new Date());

        jSpinnerCantMaxTuristas.setValue(0);
        
    }//GEN-LAST:event_jButtonAltaSalidaVaciarCamposActionPerformed

    private void jButtonAltaSalidaEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaSalidaEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAltaSalidaEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAltaDepartamentoEnviar;
    private javax.swing.JButton jButtonAltaDepartamentoVaciarCampos;
    private javax.swing.JButton jButtonAltaSalidaEnviar;
    private javax.swing.JButton jButtonAltaSalidaVaciarCampos;
    private javax.swing.JButton jButtonDepartamentoDuplicadoCancelar;
    private javax.swing.JButton jButtonDepartamentoDuplicadoReingresar;
    private javax.swing.JComboBox<String> jComboBoxActividad;
    private javax.swing.JComboBox<String> jComboBoxDepartamento;
    private javax.swing.JDialog jDialogDepartamentoDuplicado;
    private javax.swing.JInternalFrame jInternalFrameAgregarActividadPaquete;
    private javax.swing.JInternalFrame jInternalFrameAgregarUsuario;
    private javax.swing.JInternalFrame jInternalFrameAltaActividadTuristica;
    private javax.swing.JInternalFrame jInternalFrameAltaDepartamento;
    private javax.swing.JInternalFrame jInternalFrameAltaPaqueteActividades;
    private javax.swing.JInternalFrame jInternalFrameAltaSalidaTuristica;
    private javax.swing.JInternalFrame jInternalFrameConsultaActividadTuristica;
    private javax.swing.JInternalFrame jInternalFrameConsultaPaquetes;
    private javax.swing.JInternalFrame jInternalFrameConsultaSalidaTuristica;
    private javax.swing.JInternalFrame jInternalFrameConsultarUsuario;
    private javax.swing.JInternalFrame jInternalFrameInscripcionSalidaTuristica;
    private javax.swing.JInternalFrame jInternalFrameModificarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDescripcionDepartamento;
    private javax.swing.JLabel jLabelNombreDepartamento;
    private javax.swing.JLabel jLabelURLDepartamento;
    private javax.swing.JMenu jMenuAcciones;
    private javax.swing.JMenu jMenuActividad;
    private javax.swing.JMenuItem jMenuActividadAlta;
    private javax.swing.JMenuItem jMenuActividadConsulta;
    private javax.swing.JMenuItem jMenuAgregarActividadPaquete;
    private javax.swing.JMenuItem jMenuAltaPaquete;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuConsultaPaquete;
    private javax.swing.JMenuItem jMenuDepartamentoAlta;
    private javax.swing.JMenu jMenuPaquete;
    private javax.swing.JMenu jMenuSalida;
    private javax.swing.JMenuItem jMenuSalidaAlta;
    private javax.swing.JMenuItem jMenuSalidaConsulta;
    private javax.swing.JMenuItem jMenuSalidaInscripcion;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JMenuItem jMenuUsuarioAlta;
    private javax.swing.JMenuItem jMenuUsuarioConsulta;
    private javax.swing.JMenuItem jMenuUsuarioModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparatorAltaDepartamento;
    private javax.swing.JSpinner jSpinnerCantMaxTuristas;
    private javax.swing.JSpinner jSpinnerFechaAlta;
    private javax.swing.JSpinner jSpinnerFechaSalida;
    private javax.swing.JTabbedPane jTabbedPaneCasosDeUso;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldDescripcionDepartamento;
    private javax.swing.JTextField jTextFieldLugarSalida;
    private javax.swing.JTextField jTextFieldNombreDepartamento;
    private javax.swing.JTextField jTextFieldNombreSalida;
    private javax.swing.JTextField jTextFieldURLDepartamento;
    // End of variables declaration//GEN-END:variables
}
