
package webservice;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "DatatypeConfigurationException", targetNamespace = "http://webService/")
public class DatatypeConfigurationException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DatatypeConfigurationException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DatatypeConfigurationException_Exception(String message, DatatypeConfigurationException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DatatypeConfigurationException_Exception(String message, DatatypeConfigurationException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservice.DatatypeConfigurationException
     */
    public DatatypeConfigurationException getFaultInfo() {
        return faultInfo;
    }

}
