
package webservice;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WSActividadController", targetNamespace = "http://webService/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSActividadController {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WSActividadController/pingRequest", output = "http://webService/WSActividadController/pingResponse")
    public String ping();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns webservice.DtActividadesCollectionWS
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WSActividadController/obtenerActividadesTuristicasRequest", output = "http://webService/WSActividadController/obtenerActividadesTuristicasResponse")
    public DtActividadesCollectionWS obtenerActividadesTuristicas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        long arg1);

    /**
     * 
     * @return
     *     returns webservice.DtDepartamentosCollectionWS
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WSActividadController/obtenerDepartamentosRequest", output = "http://webService/WSActividadController/obtenerDepartamentosResponse")
    public DtDepartamentosCollectionWS obtenerDepartamentos();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservice.DtActividadesCollectionWS
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WSActividadController/obtenerActividadesTuristicasPorDepartamentoRequest", output = "http://webService/WSActividadController/obtenerActividadesTuristicasPorDepartamentoResponse")
    public DtActividadesCollectionWS obtenerActividadesTuristicasPorDepartamento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
