
package webservice;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WSActividadController", targetNamespace = "http://webService/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSActividadController {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WSActividadController/pingRequest", output = "http://webService/WSActividadController/pingResponse")
    public String ping();

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WSActividadController/obtenerFotoActividadTuristicaRequest", output = "http://webService/WSActividadController/obtenerFotoActividadTuristicaResponse")
    public byte[] obtenerFotoActividadTuristica(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns webservice.DtActividadesCollectionWS
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WSActividadController/obtenerActividadesTuristicasRequest", output = "http://webService/WSActividadController/obtenerActividadesTuristicasResponse")
    public DtActividadesCollectionWS obtenerActividadesTuristicas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        long arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservice.DtActividadTuristica
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WSActividadController/obtenerActividadTuristicaRequest", output = "http://webService/WSActividadController/obtenerActividadTuristicaResponse")
    public DtActividadTuristica obtenerActividadTuristica(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservice.DtActividadTuristica
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WSActividadController/obtenerActividadTuristicaNullRequest", output = "http://webService/WSActividadController/obtenerActividadTuristicaNullResponse")
    public DtActividadTuristica obtenerActividadTuristicaNull(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

    /**
     * 
     * @return
     *     returns webservice.DtDepartamentosCollectionWS
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WSActividadController/obtenerDepartamentosRequest", output = "http://webService/WSActividadController/obtenerDepartamentosResponse")
    public DtDepartamentosCollectionWS obtenerDepartamentos();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservice.DtActividadesCollectionWS
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WSActividadController/obtenerActividadesRelacionadasRequest", output = "http://webService/WSActividadController/obtenerActividadesRelacionadasResponse")
    public DtActividadesCollectionWS obtenerActividadesRelacionadas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservice.DtActividadTuristica
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WSActividadController/obtenerFotoActividadTuristicaIDRequest", output = "http://webService/WSActividadController/obtenerFotoActividadTuristicaIDResponse")
    public DtActividadTuristica obtenerFotoActividadTuristicaID(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WSActividadController/obtenerCategoriasRequest", output = "http://webService/WSActividadController/obtenerCategoriasResponse")
    public String obtenerCategorias();

    /**
     * 
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WSActividadController/obtenerCostoActividadRequest", output = "http://webService/WSActividadController/obtenerCostoActividadResponse")
    public float obtenerCostoActividad(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WSActividadController/obtenerCantidadFavoritosRequest", output = "http://webService/WSActividadController/obtenerCantidadFavoritosResponse")
    public int obtenerCantidadFavoritos(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservice.DtStringCollectionWS
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WSActividadController/obtenerActividadesFavoritasRequest", output = "http://webService/WSActividadController/obtenerActividadesFavoritasResponse")
    public DtStringCollectionWS obtenerActividadesFavoritas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://webService/WSActividadController/agregarAFavoritosRequest", output = "http://webService/WSActividadController/agregarAFavoritosResponse")
    public void agregarAFavoritos(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://webService/WSActividadController/eliminarDeFavoritosRequest", output = "http://webService/WSActividadController/eliminarDeFavoritosResponse")
    public void eliminarDeFavoritos(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservice.DtActividadesCollectionWS
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WSActividadController/obtenerActividadesTuristicasPorDepartamentoRequest", output = "http://webService/WSActividadController/obtenerActividadesTuristicasPorDepartamentoResponse")
    public DtActividadesCollectionWS obtenerActividadesTuristicasPorDepartamento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservice.DtActividadesCollectionWS
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WSActividadController/obtenerActividadesPorCategoriaRequest", output = "http://webService/WSActividadController/obtenerActividadesPorCategoriaResponse")
    public DtActividadesCollectionWS obtenerActividadesPorCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
