
package webservice;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WSLoginController", targetNamespace = "http://webService/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSLoginController {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WSLoginController/pingRequest", output = "http://webService/WSLoginController/pingResponse")
    public String ping();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservice.DtUsuarioWrapper
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/WSLoginController/obtenerUsuarioAlternativoRequest", output = "http://webService/WSLoginController/obtenerUsuarioAlternativoResponse")
    public DtUsuarioWrapper obtenerUsuarioAlternativo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
