
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "WSLoginControllerService", targetNamespace = "http://webService/", wsdlLocation = "http://localhost:8889/ws/Login?wsdl")
public class WSLoginControllerService
    extends Service
{

    private final static URL WSLOGINCONTROLLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSLOGINCONTROLLERSERVICE_EXCEPTION;
    private final static QName WSLOGINCONTROLLERSERVICE_QNAME = new QName("http://webService/", "WSLoginControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8889/ws/Login?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSLOGINCONTROLLERSERVICE_WSDL_LOCATION = url;
        WSLOGINCONTROLLERSERVICE_EXCEPTION = e;
    }

    public WSLoginControllerService() {
        super(__getWsdlLocation(), WSLOGINCONTROLLERSERVICE_QNAME);
    }

    public WSLoginControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSLOGINCONTROLLERSERVICE_QNAME, features);
    }

    public WSLoginControllerService(URL wsdlLocation) {
        super(wsdlLocation, WSLOGINCONTROLLERSERVICE_QNAME);
    }

    public WSLoginControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSLOGINCONTROLLERSERVICE_QNAME, features);
    }

    public WSLoginControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSLoginControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSLoginController
     */
    @WebEndpoint(name = "WSLoginControllerPort")
    public WSLoginController getWSLoginControllerPort() {
        return super.getPort(new QName("http://webService/", "WSLoginControllerPort"), WSLoginController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSLoginController
     */
    @WebEndpoint(name = "WSLoginControllerPort")
    public WSLoginController getWSLoginControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService/", "WSLoginControllerPort"), WSLoginController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSLOGINCONTROLLERSERVICE_EXCEPTION!= null) {
            throw WSLOGINCONTROLLERSERVICE_EXCEPTION;
        }
        return WSLOGINCONTROLLERSERVICE_WSDL_LOCATION;
    }

}
