
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "WSPaqueteControllerService", targetNamespace = "http://webService/", wsdlLocation = "http://localhost:8889/ws/Paquete?wsdl")
public class WSPaqueteControllerService
    extends Service
{

    private final static URL WSPAQUETECONTROLLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSPAQUETECONTROLLERSERVICE_EXCEPTION;
    private final static QName WSPAQUETECONTROLLERSERVICE_QNAME = new QName("http://webService/", "WSPaqueteControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8889/ws/Paquete?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSPAQUETECONTROLLERSERVICE_WSDL_LOCATION = url;
        WSPAQUETECONTROLLERSERVICE_EXCEPTION = e;
    }

    public WSPaqueteControllerService() {
        super(__getWsdlLocation(), WSPAQUETECONTROLLERSERVICE_QNAME);
    }

    public WSPaqueteControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSPAQUETECONTROLLERSERVICE_QNAME, features);
    }

    public WSPaqueteControllerService(URL wsdlLocation) {
        super(wsdlLocation, WSPAQUETECONTROLLERSERVICE_QNAME);
    }

    public WSPaqueteControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSPAQUETECONTROLLERSERVICE_QNAME, features);
    }

    public WSPaqueteControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSPaqueteControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSPaqueteController
     */
    @WebEndpoint(name = "WSPaqueteControllerPort")
    public WSPaqueteController getWSPaqueteControllerPort() {
        return super.getPort(new QName("http://webService/", "WSPaqueteControllerPort"), WSPaqueteController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSPaqueteController
     */
    @WebEndpoint(name = "WSPaqueteControllerPort")
    public WSPaqueteController getWSPaqueteControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService/", "WSPaqueteControllerPort"), WSPaqueteController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSPAQUETECONTROLLERSERVICE_EXCEPTION!= null) {
            throw WSPAQUETECONTROLLERSERVICE_EXCEPTION;
        }
        return WSPAQUETECONTROLLERSERVICE_WSDL_LOCATION;
    }

}
