
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "WSSalidaControllerService", targetNamespace = "http://webService/", wsdlLocation = "http://localhost:8889/ws/Salida?wsdl")
public class WSSalidaControllerService
    extends Service
{

    private final static URL WSSALIDACONTROLLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSSALIDACONTROLLERSERVICE_EXCEPTION;
    private final static QName WSSALIDACONTROLLERSERVICE_QNAME = new QName("http://webService/", "WSSalidaControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8889/ws/Salida?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSSALIDACONTROLLERSERVICE_WSDL_LOCATION = url;
        WSSALIDACONTROLLERSERVICE_EXCEPTION = e;
    }

    public WSSalidaControllerService() {
        super(__getWsdlLocation(), WSSALIDACONTROLLERSERVICE_QNAME);
    }

    public WSSalidaControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSALIDACONTROLLERSERVICE_QNAME, features);
    }

    public WSSalidaControllerService(URL wsdlLocation) {
        super(wsdlLocation, WSSALIDACONTROLLERSERVICE_QNAME);
    }

    public WSSalidaControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSALIDACONTROLLERSERVICE_QNAME, features);
    }

    public WSSalidaControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSSalidaControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSSalidaController
     */
    @WebEndpoint(name = "WSSalidaControllerPort")
    public WSSalidaController getWSSalidaControllerPort() {
        return super.getPort(new QName("http://webService/", "WSSalidaControllerPort"), WSSalidaController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSSalidaController
     */
    @WebEndpoint(name = "WSSalidaControllerPort")
    public WSSalidaController getWSSalidaControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService/", "WSSalidaControllerPort"), WSSalidaController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSALIDACONTROLLERSERVICE_EXCEPTION!= null) {
            throw WSSALIDACONTROLLERSERVICE_EXCEPTION;
        }
        return WSSALIDACONTROLLERSERVICE_WSDL_LOCATION;
    }

}
