
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "WSUsuarioControllerService", targetNamespace = "http://webService/", wsdlLocation = "http://localhost:8889/ws/Usuario?wsdl")
public class WSUsuarioControllerService
    extends Service
{

    private final static URL WSUSUARIOCONTROLLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSUSUARIOCONTROLLERSERVICE_EXCEPTION;
    private final static QName WSUSUARIOCONTROLLERSERVICE_QNAME = new QName("http://webService/", "WSUsuarioControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8889/ws/Usuario?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSUSUARIOCONTROLLERSERVICE_WSDL_LOCATION = url;
        WSUSUARIOCONTROLLERSERVICE_EXCEPTION = e;
    }

    public WSUsuarioControllerService() {
        super(__getWsdlLocation(), WSUSUARIOCONTROLLERSERVICE_QNAME);
    }

    public WSUsuarioControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSUSUARIOCONTROLLERSERVICE_QNAME, features);
    }

    public WSUsuarioControllerService(URL wsdlLocation) {
        super(wsdlLocation, WSUSUARIOCONTROLLERSERVICE_QNAME);
    }

    public WSUsuarioControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSUSUARIOCONTROLLERSERVICE_QNAME, features);
    }

    public WSUsuarioControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSUsuarioControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSUsuarioController
     */
    @WebEndpoint(name = "WSUsuarioControllerPort")
    public WSUsuarioController getWSUsuarioControllerPort() {
        return super.getPort(new QName("http://webService/", "WSUsuarioControllerPort"), WSUsuarioController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSUsuarioController
     */
    @WebEndpoint(name = "WSUsuarioControllerPort")
    public WSUsuarioController getWSUsuarioControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService/", "WSUsuarioControllerPort"), WSUsuarioController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSUSUARIOCONTROLLERSERVICE_EXCEPTION!= null) {
            throw WSUSUARIOCONTROLLERSERVICE_EXCEPTION;
        }
        return WSUSUARIOCONTROLLERSERVICE_WSDL_LOCATION;
    }

}
